name: Release

on:
    push:
        branches:
            - master
        paths-ignore:
            - 'package.json'
            - 'CHANGELOG.md'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install
              run: npm ci

            - name: Configure git
              run: |
                  git config user.email "laurilavanti@gmail.com"
                  git config user.name "Lauri Lavanti"

            - name: Release
              run: npm run release

            - name: Test
              run: echo ${{ secrets.PAT }}

            - name: Set origin
              run: git remote set-url origin https://lapanti:${{ secrets.PAT }}@github.com/lapanti/lapanti.github.io.git

            - name: Push changes
              run: git push --follow-tags
